# File: docker-compose.yml

version: "3.11"
services:
  backend:
    build: ./backend
    command: >
      bash -c "python init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
